---
- name: Reload nginx
  service: 
    name: nignx
    state: reloaded
  listen: "Reload web services"

- name: Validate that the http_port is working
  wait_for:
    host: "{{ ansible_host }}"
    port: "{{ http_port }}"
    timeout: 5
  connection: local
  listen: "Reload web service"
