---
- hosts: webservers
  become: true
  tasks:
    - name: Ensure nginx is installed
      apt:
        name: nginx
        state: present

    - name: Configure nginx
      template:
        src: nginx-default.j2
        dest: /etc/nginx/sites-available/default
        mode: u=rw,g=r,o=r

    - name: Reload nginx for new config
      service:
       name: nginx
       state: reloaded

    - name: Push website content to the web root
      template:
        src: index.html.j2
        dest: /var/www/html/index.html
        mode: u=rw,g=r,o=r

    - name: index.html also know as main.html
      file:
        state: link
        src: /var/www/html/index.html
        dest: /var/www/html/main.html

    - name: Update the Website content
      lineinfile:
        path: /var/www/html/index.html
        line: "Just re-decorating a little!"
 
    - name: Firewall - Allow SSH connections
      ufw:
        rule: allow
        name: OpenSSH

    - name: Firewall - Allow Website connections
      ufw:
        rule: allow
        port: "{{ http_port }}"
  
    - name: Firewall - Deny everything else
      ufw:
        state: enabled
        policy: deny

    - name: Validate that the http_port is working
      wait_for:
        host: "{{ ansible_host }}"
        port: "{{ http_port }}"
        timeout: 5
      connection: local
